Support additional emoji types
sindresorhus/skin-tone pull request #6
Opened 2024-01-03 08:34 UTC by darkmark1991

fixes #5 + adds support for multi component emojis (couples, detective, etc.)

### Changes

1.  Update the check to see if emoji is skin tone compatible.
- This means that emoji has less than 3 modifiable components (3+ are families, there is no plans to support skin tone for those at this stage https://www.unicode.org/L2/L2020/20114-family-emoji-explor.pdf)
- For the several two-person family emojis additional check was added
2. Exclude `Unicode Variation Selector` character unless it's at the end of an emoji, as it interferes with skin tone application
3. Apply skin tone to the right of every modifiable character (couples, etc.)
4. Fix skin tone removal to remove from all modifiable characters (couples, etc.)

2024-01-03 14:44 UTC, sindresorhus commented
Thanks for working on this. Can you add some tests?

2024-01-03 14:50 UTC, sindresorhus requested changes

2024-01-03 14:50 UTC, sindresorhus commented on index.js
> +		for (let i = 0; i < emojiArray.length; i++) {
Use a `for-of` loop. You then also don't need `[...emoji]`.

2024-01-03 14:50 UTC, sindresorhus commented on index.js
> +const twoFamilyEmojis = new Set(['👩‍👦', '👩‍👧', '👨‍👧', '👨‍👦']);
This needs a code comment on why it's hard-coded.

2024-01-03 14:50 UTC, sindresorhus commented on index.js
> +const unicodeVariationSelector = '\uFE0F';
```suggestion
const unicodeVariationSelector = '\u{FE0F}';
```

2024-01-03 21:14 UTC, darkmark1991 commented
@sindresorhus Hey, thanks for reviewing so quickly! Made requested modifications & added some comments, hope it's better now 🙏

2024-01-07 11:02 UTC, sindresorhus requested changes

2024-01-07 11:02 UTC, sindresorhus commented on index.js
> +// So it should be removed if present, otherwise it causes issues like this '🕵🏼️‍♀️'
> like this '🕵🏼️‍♀️'

Not immediately clear what the problem with that emoji is. Should be described for clarity.

2024-01-07 11:02 UTC, sindresorhus commented on index.js
> +const emojiBaseModifierRegex = /\p{Emoji_Modifier_Base}/ug;
Regex with global flag is mutable and should not be at the top-level.

2024-01-07 11:02 UTC, sindresorhus commented on index.js
> +	if (tone !== 'none' && (emoji).match(emojiBaseModifierRegex)?.length < 3 && !twoFamilyEmojis.has(emoji)) {
Do an early return to reduce nesting.

2024-01-07 23:40 UTC, merged

2024-01-07 23:40 UTC, sindresorhus commented
Thanks :)